# Assignment 13B

**Name:** Bilal Khan

**Email:** bilal.khan@live.com

## Question
Perform ydata profiling on two different datasets.

In [2]:
# import libraries
import pandas as pd 
import ydata_profiling as yd

In [7]:
# load dataset
df = pd.read_csv('../data/mtcars.csv')
df.head(10)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [11]:
# Use profiling on the mtcars dataset 
cars_dataset_profiling = yd.ProfileReport(df)
cars_dataset_profiling.to_file(output_file="../output/13b_mtcars_dataset_profiling.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 70/70 [00:07<00:00,  9.29it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 505.64it/s]

##### Purpose of performing `ydata-profiling` on the above dataset mtcars is as follows:

Performing ydata profiling on this data through exploration and visualization of feature distributions, outliers, missing values etc. would serve important purposes:

1. It would give an overview of the data dimensions, types and structure upfront to understand the problem domain.

2. Identifying missing or outlier values through profiling helps data cleaning/pre-processing.

3. Visualizing correlations between features like study hours and scores helps validate assumptions of linear relationships.


In summary, ydata profiling is critical to understand this sample linear regression dataset, validate key assumptions, prepare the data and select appropriate features for model building and hyperparameter tuning.